version: '3.4'

services:
  splitten.webapi:
    image: splitten
    container_name: splitten
    build: 
        context: .
        dockerfile: Dockerfile 
    networks:
        - splitten_network
  pwsh.container:
    image: splitten_pwsh
    container_name: pwsh4
    build:
        context: ../pwsh
        dockerfile: Dockerfile
    networks:
        - splitten_network
    depends_on:
        - splitten.webapi
networks:
  splitten_network:
    driver: bridge